config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'home#index'
  get 'home/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to event_url(@event), notice: "Evento criado com sucesso!" }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to event_url(@event), notice: "Evento atualizado com sucesso!" }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: "Evento excluído com sucesso!" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :date, :location, :description)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/events/_event.html.erb
<div id="<%= dom_id event %>">
  <p> Evento:
    
    <%= event.name %>
  </p>

  <p> Data:
    
    <%= event.date %>
  </p>

  <p> Local:
    
    <%= event.location %>
  </p>

  <p> Descrição:
    
    <%= event.description %>
  </p>

</div>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Nome, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
  <%= form.label :Local, style: "display: block" %>
  <%= form.text_field :location %>
</div>

  <div>
    <%= form.label :Data, style: "display: block" %>
    <%= form.datetime_field :date %>
  </div>
  
  <div>
    <%= form.label :Descrição, style: "display: block" %>
    <%= form.text_field :description %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editar Evento</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Detalhar", @event %> |
  <%= link_to "Voltar para Eventos", events_path %>
</div>

app/views/events/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Eventos</h1>

<table  class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Evento</th>
      <th>Data</th>
      <th>Local</th>
      <th>Descrição</th>
      <th colspan='3'></th>
      <th colspan='3'></th>
    </tr>
  </thead>


   <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name  %></td>
        <td><%= event.date  %></td>
        <td><%= event.location  %></td>
        <td><%= event.description  %></td>
        <td><%= link_to 'Detalhes', event  %></td>
        <td><%= link_to 'Editar', edit_event_path(event) %></td>   
        <td><%= link_to "Excluir", event,method: :delete, data: {turbo_confirm: "Excluir Evento. Tem certeza?"}, class:"link-danger" %> </td>
        <td><%= link_to 'Inscrever-se' %></td>
      </tr>
    <% end %>
   </tbody>
 </table>

<br>

<%= link_to 'Novo evento', new_event_path, class:"btn btn-secondary" %>

app/views/events/new.html.erb
<h1>Novo Evento</h1>

<%= render "form", event: @event %>

<br>

<div>
  <%= link_to "Voltar para Eventos", events_path %>
</div>

app/views/events/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @event %>

<div>
  <%= link_to "Editar", edit_event_path(@event) %> |
  <%= link_to "Voltar para Eventos", events_path %>

  <%= button_to "Excluir", @event, method: :delete, data: {turbo_confirm: "Excluir Evento. Tem certeza?"}, class:"btn - btn-danger" %> 
</div>

app/views/home/_footer.html.erb
<!-- app/views/shared/_footer.html.erb -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <h4>Informações de Contato</h4>
        <p>Endereço: [Endereço da Escola]</p>
        <p>Telefone: [Telefone da Escola]</p>
        <p>Email: [Email da Escola]</p>
      </div>
      <div class="col-md-3">
        <h4>Redes Sociais</h4>
        <ul class="list-unstyled">
          <li><a href="[Link para a página do Facebook]">Facebook</a></li>
          <li><a href="[Link para o Twitter]">Twitter</a></li>
          <li><a href="[Link para o Instagram]">Instagram</a></li>
        </ul>
      </div>
      <div class="col-md-3">
        <h4>Links Úteis</h4>
        <ul class="list-unstyled">
          <li><a href="[Link para a Política de Privacidade]">Política de Privacidade</a></li>
          <li><a href="[Link para Trabalhe Conosco]">Trabalhe Conosco</a></li>
        </ul>
      </div>

      <div class="bg-secondary text-white text-center py-2">
      <button class="btn btn-dark btn-sm" id="scroll-to-top">
          <i class="fas fa-arrow-up"></i> Voltar ao Topo
      </button>
      </div>

    </div>
  </div>
</footer>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
<%= link_to 'ESFA', root_path, class:"navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Início', root_path, class:"nav-link" %>
        
      </li>
      <li class="nav-item">
        <%= link_to 'A Escola', home_about_path, class:"nav-link" %>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Infantil</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Fundamental I</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Fundamental II</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-expanded="false">
          Serviços
        </a>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Pré-Matrícula</a>
          <a class="dropdown-item" href="#">2º via de boleto</a>
          <%= link_to 'Eventos', events_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Aluguel da quadra</a>
          <a class="dropdown-item" href="#">Aluguel de salas</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Galeria</a>
      </li>
      
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Buscar" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
    </form>
  </div>
</nav>

app/views/home/about.html.erb
<h1> Sobre a ESFA... </h1>

app/views/home/index.html.erb
     

<h1>Home#index</h1>
<p>esfa web app</p>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="pt-br">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag 'application', 'custom' %>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">

    <title>Escola São Francisco de Assis</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

 
  </head>
  <body>

  <%= render 'home/header' %>
  <div class="container">
  <br/>
  <%= yield %>
  <footer>
    <%= render 'home/footer' %>
  </footer>
  </div>
  

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

    
  </body>
</html>